#!/usr/bin/env bash

# e - script stops on error (return !=0)
# u - error if undefined variable
# o pipefail - script fails if one of piped command fails
# x - output each line (debug)
set -euo pipefail

VERSION="0.3"

REPO_ACCOUNT="polirritmico"
REPO_NAME="ansible"
REPO_SERVER="https://github.com/"
REPO_URL="${REPO_SERVER}${REPO_ACCOUNT}/${REPO_NAME}.git"
REPO_BRANCH="main"
REPO_DIR="/tmp/ansible"

PACKAGES_TO_INSTALL=( "git" "ansible" )

#-------------------------------------------------------------------------------
# Functions definitions
#-------------------------------------------------------------------------------

install_packages() {
    package_manager_install() {
        # TODO: Check the packages and remove the installed ones from the list
        local command=$1
        local packages="${PACKAGES_TO_INSTALL[*]}"
        eval "$command $packages"
    }

    echo -e "Installing needed packages..."
    echo -e "Current settings:"
    echo -e "  - PACKAGES_TO_INSTALL: ${PACKAGES_TO_INSTALL[*]}\n"

    # Detect distro
    if [ -f /etc/os-release ]; then
        source /etc/os-release
        DISTRO=$ID
    elif [ -f /etc/lsb-release ]; then
        source /etc/lsb-release
        DISTRO=$DISTRIB_ID
    fi

    if [ "$DISTRO" == "gentoo" ]; then
        PACKAGES_TO_INSTALL=( "dev-vcs/git" "app-admin/ansible" )
        package_manager_install "emerge -av"
    elif [ "$DISTRO"  == "fedora" ]; then
        PACKAGES_TO_INSTALL=( "git" "ansible" "openssl" )
        package_manager_install "sudo dnf install -y"
    elif [ "$DISTRO" == "ubuntu" ]; then
        package_manager_install "sudo apt install -y"
    elif [ "$DISTRO" == "centos" ]; then
        package_manager_install "sudo yum install -y"
    else
        echo "Error: Unsupported distro."
        echo "       Install manually and modify the script to not run install_packages"
        exit 1
    fi

    echo "Packages installed"
}

#----------------------------------------

clone_repository() {
    echo -e "Clonning the ansible repo '${REPO_URL}' into '${REPO_DIR}'..."
    if [[ -d $REPO_DIR ]]; then
        echo -e "Found '${REPO_DIR}' directory. Removing..."
        rm -rfI ${REPO_DIR}
    fi
    echo -en "Enter PAT passphrase: "
    read -sr passphrase

    echo # echo -n "token" | openssl enc -aes-256-cbc -a -salt -pbkdf2 -pass pass:key
    token=$( echo "U2FsdGVkX18t6A27A7u4sw0H3EpoKqkHWosxk+tuw9mm5sLnMNMqNmzSBTYfJZ/q4MgbI6o9dsutKL8Xw/Ic9CWLfUy3H5PAkFsXVeNLnil1lTgtPcdlt7+Q6J5L3L/DXXLk4S62q6JO1+4Cl0oGjQ==" | \
        openssl enc -aes-256-cbc -d -a -pbkdf2 -pass pass:"${passphrase}" )

    git clone --recurse-submodules -j2 -b "$REPO_BRANCH" "https://${token}@github.com/${REPO_ACCOUNT}/${REPO_NAME}.git" "${REPO_DIR}"
    echo -e "Cloned repository into '${REPO_DIR}'"
}

#----------------------------------------

execute_ansible_playbook() {
    echo "Executing the Ansible playbook"
    pushd "${REPO_DIR}"
    ansible-playbook --ask-vault-pass --ask-become-pass main.yml
    popd
}

#-------------------------------------------------------------------------------
# Script execution
#-------------------------------------------------------------------------------

echo -e "========================================n"
echo -e "Executing bootstrap script version ${VERSION}:"
echo -e "========================================n"

install_packages

clone_repository

execute_ansible_playbook

echo "Done. Use: 'source ~/.bashrc' to reload the aliases"
